package Model.entities.commonObjectives;

import Model.entities.Card;
import Model.entities.Shelf;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import util.Config;

import java.util.ArrayList;
import java.util.List;

class CommonObjective9Test {

    Shelf shelfOne;
    Shelf shelfTwo;
    Shelf shelfThree;
    Shelf shelfFour;
    Shelf shelfFive;
    Shelf shelfSix;
    List<Card> cards;
    CommonObjective9 commonObjective9;

    /**
     * Construct various shelves and an array of cards
     */
    @BeforeEach
    void setup(){
        Config.initialise(2);
        shelfOne = new Shelf();
        shelfTwo = new Shelf();
        shelfThree = new Shelf();
        shelfFour = new Shelf();
        shelfFive = new Shelf();
        shelfSix = new Shelf();
        cards = new ArrayList<>();
        commonObjective9 = new CommonObjective9(4);
    }

    @Test
    void CommonObjective9() {
        cards.add(new Card(Card.Type.CAT,2));
        cards.add(new Card(Card.Type.GAME,0));
        cards.add(new Card(Card.Type.TROPHY,0));
        cards.add(new Card(Card.Type.FRAME,0));
        cards.add(new Card(Card.Type.CAT,1));
        cards.add(new Card(Card.Type.CAT,0));
        shelfOne.insert(cards,0);
        cards.clear();
        cards.add(new Card(Card.Type.TROPHY,1));
        cards.add(new Card(Card.Type.FRAME,1));
        cards.add(new Card(Card.Type.CAT,6));
        cards.add(new Card(Card.Type.CAT,5));
        cards.add(new Card(Card.Type.CAT,4));
        cards.add(new Card(Card.Type.CAT,3));
        shelfOne.insert(cards,1);
        cards.clear();
        cards.add(new Card(Card.Type.CAT,12));
        cards.add(new Card(Card.Type.CAT,11));
        cards.add(new Card(Card.Type.CAT,10));
        cards.add(new Card(Card.Type.CAT,9));
        cards.add(new Card(Card.Type.CAT,8));
        cards.add(new Card(Card.Type.CAT,7));
        shelfOne.insert(cards,2);
        cards.clear();
        cards.add(new Card(Card.Type.GAME,2));
        cards.add(new Card(Card.Type.CAT,13));
        cards.add(new Card(Card.Type.PLANT,0));
        cards.add(new Card(Card.Type.GAME,1));
        cards.add(new Card(Card.Type.TROPHY,2));
        cards.add(new Card(Card.Type.FRAME,2));
        shelfOne.insert(cards,3);
        cards.clear();
        cards.add(new Card(Card.Type.FRAME,4));
        cards.add(new Card(Card.Type.GAME,5));
        cards.add(new Card(Card.Type.GAME,4));
        cards.add(new Card(Card.Type.GAME,3));
        cards.add(new Card(Card.Type.TROPHY,3));
        cards.add(new Card(Card.Type.FRAME,3));
        shelfOne.insert(cards,4);
        cards.clear();
        assert (commonObjective9.verify(shelfOne));

        cards.add(new Card(Card.Type.CAT,2));
        cards.add(new Card(Card.Type.GAME,0));
        cards.add(new Card(Card.Type.TROPHY,0));
        cards.add(new Card(Card.Type.FRAME,0));
        cards.add(new Card(Card.Type.CAT,1));
        cards.add(new Card(Card.Type.CAT,0));
        shelfTwo.insert(cards,0);
        cards.clear();
        cards.add(new Card(Card.Type.TROPHY,1));
        cards.add(new Card(Card.Type.FRAME,1));
        cards.add(new Card(Card.Type.GAME,10));
        cards.add(new Card(Card.Type.CAT,5));
        cards.add(new Card(Card.Type.CAT,4));
        cards.add(new Card(Card.Type.CAT,3));
        shelfTwo.insert(cards,1);
        cards.clear();
        cards.add(new Card(Card.Type.CAT,12));
        cards.add(new Card(Card.Type.CAT,11));
        cards.add(new Card(Card.Type.CAT,10));
        cards.add(new Card(Card.Type.CAT,9));
        cards.add(new Card(Card.Type.CAT,8));
        cards.add(new Card(Card.Type.CAT,7));
        shelfTwo.insert(cards,2);
        cards.clear();
        cards.add(new Card(Card.Type.GAME,2));
        cards.add(new Card(Card.Type.CAT,13));
        cards.add(new Card(Card.Type.PLANT,0));
        cards.add(new Card(Card.Type.GAME,1));
        cards.add(new Card(Card.Type.TROPHY,2));
        cards.add(new Card(Card.Type.FRAME,2));
        shelfTwo.insert(cards,3);
        cards.clear();
        cards.add(new Card(Card.Type.FRAME,4));
        cards.add(new Card(Card.Type.GAME,5));
        cards.add(new Card(Card.Type.GAME,4));
        cards.add(new Card(Card.Type.GAME,3));
        cards.add(new Card(Card.Type.TROPHY,3));
        cards.add(new Card(Card.Type.FRAME,3));
        shelfTwo.insert(cards,4);
        cards.clear();
        assert (!commonObjective9.verify(shelfTwo));

        cards.add(new Card(Card.Type.CAT,2));
        cards.add(new Card(Card.Type.GAME,0));
        cards.add(new Card(Card.Type.TROPHY,0));
        cards.add(new Card(Card.Type.FRAME,0));
        cards.add(new Card(Card.Type.CAT,1));
        cards.add(new Card(Card.Type.CAT,0));
        shelfThree.insert(cards,0);
        cards.clear();
        cards.add(new Card(Card.Type.TROPHY,1));
        cards.add(new Card(Card.Type.FRAME,1));
        cards.add(new Card(Card.Type.TROPHY,19));
        cards.add(new Card(Card.Type.CAT,5));
        cards.add(new Card(Card.Type.FRAME,20));
        cards.add(new Card(Card.Type.CAT,3));
        shelfThree.insert(cards,1);
        cards.clear();
        cards.add(new Card(Card.Type.CAT,12));
        cards.add(new Card(Card.Type.CAT,11));
        cards.add(new Card(Card.Type.CAT,10));
        cards.add(new Card(Card.Type.CAT,9));
        cards.add(new Card(Card.Type.CAT,8));
        cards.add(new Card(Card.Type.CAT,7));
        shelfThree.insert(cards,2);
        cards.clear();
        cards.add(new Card(Card.Type.TROPHY,9));
        cards.add(new Card(Card.Type.TROPHY,13));
        cards.add(new Card(Card.Type.TROPHY,8));
        cards.add(new Card(Card.Type.FRAME,7));
        cards.add(new Card(Card.Type.FRAME,6));
        cards.add(new Card(Card.Type.FRAME,5));
        shelfThree.insert(cards,3);
        cards.clear();
        cards.add(new Card(Card.Type.FRAME,4));
        cards.add(new Card(Card.Type.GAME,5));
        cards.add(new Card(Card.Type.GAME,4));
        cards.add(new Card(Card.Type.GAME,3));
        cards.add(new Card(Card.Type.TROPHY,3));
        cards.add(new Card(Card.Type.FRAME,3));
        shelfThree.insert(cards,4);
        cards.clear();
        assert (commonObjective9.verify(shelfThree));

        cards.add(new Card(Card.Type.CAT,2));
        cards.add(new Card(Card.Type.GAME,0));
        cards.add(new Card(Card.Type.TROPHY,0));
        cards.add(new Card(Card.Type.FRAME,0));
        cards.add(new Card(Card.Type.CAT,1));
        cards.add(new Card(Card.Type.CAT,0));
        shelfFour.insert(cards,0);
        cards.clear();
        cards.add(new Card(Card.Type.TROPHY,1));
        cards.add(new Card(Card.Type.FRAME,1));
        cards.add(new Card(Card.Type.GAME,10));
        cards.add(new Card(Card.Type.CAT,5));
        cards.add(new Card(Card.Type.CAT,4));
        cards.add(new Card(Card.Type.CAT,3));
        shelfFour.insert(cards,1);
        cards.clear();
        cards.add(new Card(Card.Type.CAT,12));
        cards.add(new Card(Card.Type.CAT,11));
        cards.add(new Card(Card.Type.TROPHY,10));
        cards.add(new Card(Card.Type.FRAME,9));
        cards.add(new Card(Card.Type.GAME,18));
        cards.add(new Card(Card.Type.CAT,7));
        shelfFour.insert(cards,2);
        cards.clear();
        cards.add(new Card(Card.Type.GAME,2));
        cards.add(new Card(Card.Type.CAT,13));
        cards.add(new Card(Card.Type.PLANT,0));
        cards.add(new Card(Card.Type.GAME,1));
        cards.add(new Card(Card.Type.TROPHY,2));
        cards.add(new Card(Card.Type.FRAME,2));
        shelfFour.insert(cards,3);
        cards.clear();
        cards.add(new Card(Card.Type.FRAME,4));
        cards.add(new Card(Card.Type.GAME,5));
        cards.add(new Card(Card.Type.PLANT,4));
        cards.add(new Card(Card.Type.GAME,3));
        cards.add(new Card(Card.Type.TROPHY,3));
        cards.add(new Card(Card.Type.FRAME,3));
        shelfFour.insert(cards,4);
        cards.clear();
        assert (!commonObjective9.verify(shelfFour));

        cards.add(new Card(Card.Type.CAT,2));
        cards.add(new Card(Card.Type.GAME,0));
        cards.add(new Card(Card.Type.TROPHY,0));
        cards.add(new Card(Card.Type.FRAME,0));
        cards.add(new Card(Card.Type.CAT,1));
        shelfFive.insert(cards,0);
        cards.clear();
        cards.add(new Card(Card.Type.CAT,21));
        cards.add(new Card(Card.Type.FRAME,1));
        cards.add(new Card(Card.Type.GAME,10));
        cards.add(new Card(Card.Type.CAT,5));
        cards.add(new Card(Card.Type.CAT,4));
        cards.add(new Card(Card.Type.CAT,3));
        shelfFive.insert(cards,1);
        cards.clear();
        cards.add(new Card(Card.Type.CAT,12));
        cards.add(new Card(Card.Type.CAT,11));
        cards.add(new Card(Card.Type.FRAME,21));
        cards.add(new Card(Card.Type.FRAME,9));
        cards.add(new Card(Card.Type.GAME,18));
        cards.add(new Card(Card.Type.CAT,7));
        shelfFive.insert(cards,2);
        cards.clear();
        cards.add(new Card(Card.Type.GAME,2));
        cards.add(new Card(Card.Type.CAT,13));
        cards.add(new Card(Card.Type.PLANT,0));
        cards.add(new Card(Card.Type.GAME,1));
        shelfFive.insert(cards,3);
        cards.clear();
        cards.add(new Card(Card.Type.FRAME,4));
        cards.add(new Card(Card.Type.GAME,5));
        cards.add(new Card(Card.Type.GAME,6));
        cards.add(new Card(Card.Type.GAME,3));
        cards.add(new Card(Card.Type.TROPHY,3));
        cards.add(new Card(Card.Type.FRAME,3));
        shelfFive.insert(cards,4);
        cards.clear();
        assert (commonObjective9.verify(shelfFive));

        cards.add(new Card(Card.Type.CAT,2));
        cards.add(new Card(Card.Type.GAME,0));
        cards.add(new Card(Card.Type.TROPHY,0));
        cards.add(new Card(Card.Type.FRAME,0));
        cards.add(new Card(Card.Type.CAT,1));
        shelfSix.insert(cards,0);
        cards.clear();
        cards.add(new Card(Card.Type.CAT,21));
        cards.add(new Card(Card.Type.FRAME,1));
        cards.add(new Card(Card.Type.GAME,10));
        cards.add(new Card(Card.Type.CAT,5));
        cards.add(new Card(Card.Type.CAT,4));
        shelfSix.insert(cards,1);
        cards.clear();
        cards.add(new Card(Card.Type.CAT,12));
        cards.add(new Card(Card.Type.CAT,11));
        cards.add(new Card(Card.Type.FRAME,21));
        cards.add(new Card(Card.Type.FRAME,9));
        cards.add(new Card(Card.Type.GAME,18));
        cards.add(new Card(Card.Type.CAT,7));
        shelfSix.insert(cards,2);
        cards.clear();
        cards.add(new Card(Card.Type.GAME,2));
        cards.add(new Card(Card.Type.CAT,13));
        cards.add(new Card(Card.Type.PLANT,0));
        cards.add(new Card(Card.Type.GAME,1));
        shelfSix.insert(cards,3);
        cards.clear();
        cards.add(new Card(Card.Type.FRAME,4));
        cards.add(new Card(Card.Type.GAME,5));
        cards.add(new Card(Card.Type.GAME,6));
        cards.add(new Card(Card.Type.GAME,3));
        cards.add(new Card(Card.Type.TROPHY,3));
        cards.add(new Card(Card.Type.FRAME,3));
        shelfSix.insert(cards,4);
        assert (!commonObjective9.verify(shelfSix));
    }
}